version: '3'

services:
  db:
    image: postgres:16
    container_name: ekygai-db
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ekygai-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ekygai-api
    restart: always
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_HOST=ekygai-db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ConnectionStrings__DefaultConnection=Host=ekygai-db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWT_TOKEN_KEY=${JWT_TOKEN_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
    depends_on:
      - db
    networks:
      - ekygai-network

  frontend:
    build:
      context: ./frontend/web-app
      dockerfile: Dockerfile
    container_name: ekygai-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - SERVER_API_URL=${SERVER_API_URL}
    depends_on:
      - api
    networks:
      - ekygai-network

networks:
  ekygai-network:

volumes:
  postgres-data: