services:
  db:
    image: postgres:16
    container_name: ekygai-db
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ekygai-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ekygai-api
    restart: always
    # Expose the API on host port 5000 → container port 80
    ports:
      - "5000:80"
    env_file:
      - .env.local
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST:-ekygai-db};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - JWTSettings__TokenKey=${JWT_TOKEN_KEY}
      - JWTSettings__Issuer=${JWT_ISSUER}
      - JWTSettings__Audience=${JWT_AUDIENCE}
    depends_on:
      - db
    networks:
      - ekygai-network

  frontend:
    build:
      context: ./frontend/web-app
      dockerfile: Dockerfile
    container_name: ekygai-frontend
    restart: always
    # Expose Next.js on host port 3000 → container port 3000
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      # Next.js environment variables
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - api
    networks:
      - ekygai-network

networks:
  ekygai-network:

volumes:
  postgres-data:
