services:
  db:
    image: postgres:16
    container_name: ekygai-db
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env.local
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ekygai-network

  app:
    build:
      context: .
      dockerfile: Dockerfile  # The combined Dockerfile
    container_name: ekygai-app
    restart: always
    ports:
      - "${API_PORT:-5000}:80"         # Maps .NET API port 80 inside container → 5000 on host
      - "${FRONTEND_PORT:-3000}:3000"  # Maps Next.js port 3000 inside container → 3000 on host
    env_file:
      - .env.local
    environment:
      # .NET app base URL
      - ASPNETCORE_URLS=http://+:80
      # Environment
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      
      # Dynamic DB connection
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST:-ekygai-db};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}

      # Next.js environment
      - NODE_ENV=${NODE_ENV}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

      # JWT environment variables (for TokenKey, Issuer, Audience)
      - JWTSettings__TokenKey=${JWT_TOKEN_KEY}
      - JWTSettings__Issuer=${JWT_ISSUER}
      - JWTSettings__Audience=${JWT_AUDIENCE}

    depends_on:
      - db
    networks:
      - ekygai-network

networks:
  ekygai-network:

volumes:
  postgres-data:
